/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VinculosRouteImport } from './routes/vinculos'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ProfessoresRouteImport } from './routes/professores'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as OrdemRouteImport } from './routes/ordem'
import { Route as FigurinosRouteImport } from './routes/figurinos'
import { Route as FestivaisRouteImport } from './routes/festivais'
import { Route as CoreografiasRouteImport } from './routes/coreografias'
import { Route as ConflitosRouteImport } from './routes/conflitos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as BailarinosRouteImport } from './routes/bailarinos'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as IndexRouteImport } from './routes/index'

const VinculosRoute = VinculosRouteImport.update({
  id: '/vinculos',
  path: '/vinculos',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessoresRoute = ProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdemRoute = OrdemRouteImport.update({
  id: '/ordem',
  path: '/ordem',
  getParentRoute: () => rootRouteImport,
} as any)
const FigurinosRoute = FigurinosRouteImport.update({
  id: '/figurinos',
  path: '/figurinos',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivaisRoute = FestivaisRouteImport.update({
  id: '/festivais',
  path: '/festivais',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreografiasRoute = CoreografiasRouteImport.update({
  id: '/coreografias',
  path: '/coreografias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflitosRoute = ConflitosRouteImport.update({
  id: '/conflitos',
  path: '/conflitos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const BailarinosRoute = BailarinosRouteImport.update({
  id: '/bailarinos',
  path: '/bailarinos',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/aulas': typeof AulasRoute
  '/bailarinos': typeof BailarinosRoute
  '/caixa': typeof CaixaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conflitos': typeof ConflitosRoute
  '/coreografias': typeof CoreografiasRoute
  '/festivais': typeof FestivaisRoute
  '/figurinos': typeof FigurinosRoute
  '/ordem': typeof OrdemRoute
  '/pagamentos': typeof PagamentosRoute
  '/professores': typeof ProfessoresRoute
  '/timeline': typeof TimelineRoute
  '/vinculos': typeof VinculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/aulas': typeof AulasRoute
  '/bailarinos': typeof BailarinosRoute
  '/caixa': typeof CaixaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conflitos': typeof ConflitosRoute
  '/coreografias': typeof CoreografiasRoute
  '/festivais': typeof FestivaisRoute
  '/figurinos': typeof FigurinosRoute
  '/ordem': typeof OrdemRoute
  '/pagamentos': typeof PagamentosRoute
  '/professores': typeof ProfessoresRoute
  '/timeline': typeof TimelineRoute
  '/vinculos': typeof VinculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/aulas': typeof AulasRoute
  '/bailarinos': typeof BailarinosRoute
  '/caixa': typeof CaixaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conflitos': typeof ConflitosRoute
  '/coreografias': typeof CoreografiasRoute
  '/festivais': typeof FestivaisRoute
  '/figurinos': typeof FigurinosRoute
  '/ordem': typeof OrdemRoute
  '/pagamentos': typeof PagamentosRoute
  '/professores': typeof ProfessoresRoute
  '/timeline': typeof TimelineRoute
  '/vinculos': typeof VinculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apresentacao'
    | '/aulas'
    | '/bailarinos'
    | '/caixa'
    | '/configuracoes'
    | '/conflitos'
    | '/coreografias'
    | '/festivais'
    | '/figurinos'
    | '/ordem'
    | '/pagamentos'
    | '/professores'
    | '/timeline'
    | '/vinculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apresentacao'
    | '/aulas'
    | '/bailarinos'
    | '/caixa'
    | '/configuracoes'
    | '/conflitos'
    | '/coreografias'
    | '/festivais'
    | '/figurinos'
    | '/ordem'
    | '/pagamentos'
    | '/professores'
    | '/timeline'
    | '/vinculos'
  id:
    | '__root__'
    | '/'
    | '/apresentacao'
    | '/aulas'
    | '/bailarinos'
    | '/caixa'
    | '/configuracoes'
    | '/conflitos'
    | '/coreografias'
    | '/festivais'
    | '/figurinos'
    | '/ordem'
    | '/pagamentos'
    | '/professores'
    | '/timeline'
    | '/vinculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApresentacaoRoute: typeof ApresentacaoRoute
  AulasRoute: typeof AulasRoute
  BailarinosRoute: typeof BailarinosRoute
  CaixaRoute: typeof CaixaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConflitosRoute: typeof ConflitosRoute
  CoreografiasRoute: typeof CoreografiasRoute
  FestivaisRoute: typeof FestivaisRoute
  FigurinosRoute: typeof FigurinosRoute
  OrdemRoute: typeof OrdemRoute
  PagamentosRoute: typeof PagamentosRoute
  ProfessoresRoute: typeof ProfessoresRoute
  TimelineRoute: typeof TimelineRoute
  VinculosRoute: typeof VinculosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vinculos': {
      id: '/vinculos'
      path: '/vinculos'
      fullPath: '/vinculos'
      preLoaderRoute: typeof VinculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professores': {
      id: '/professores'
      path: '/professores'
      fullPath: '/professores'
      preLoaderRoute: typeof ProfessoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordem': {
      id: '/ordem'
      path: '/ordem'
      fullPath: '/ordem'
      preLoaderRoute: typeof OrdemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figurinos': {
      id: '/figurinos'
      path: '/figurinos'
      fullPath: '/figurinos'
      preLoaderRoute: typeof FigurinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivais': {
      id: '/festivais'
      path: '/festivais'
      fullPath: '/festivais'
      preLoaderRoute: typeof FestivaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coreografias': {
      id: '/coreografias'
      path: '/coreografias'
      fullPath: '/coreografias'
      preLoaderRoute: typeof CoreografiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflitos': {
      id: '/conflitos'
      path: '/conflitos'
      fullPath: '/conflitos'
      preLoaderRoute: typeof ConflitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bailarinos': {
      id: '/bailarinos'
      path: '/bailarinos'
      fullPath: '/bailarinos'
      preLoaderRoute: typeof BailarinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApresentacaoRoute: ApresentacaoRoute,
  AulasRoute: AulasRoute,
  BailarinosRoute: BailarinosRoute,
  CaixaRoute: CaixaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConflitosRoute: ConflitosRoute,
  CoreografiasRoute: CoreografiasRoute,
  FestivaisRoute: FestivaisRoute,
  FigurinosRoute: FigurinosRoute,
  OrdemRoute: OrdemRoute,
  PagamentosRoute: PagamentosRoute,
  ProfessoresRoute: ProfessoresRoute,
  TimelineRoute: TimelineRoute,
  VinculosRoute: VinculosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
